logging:
  level:
    root: warn
    org:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

spring:
  jackson:
    default-property-inclusion: non-null
my:
  secretkey: 0d000721